<?php

namespace AppBundle\Repository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRealUrl($shortUrl){
        $data = $this->findOneBy(
            array(
                'shortUrl'=>$shortUrl
            )
        );
        if(is_null($data)){
            return null;
        }
        return $data->getUrl();
    }

    public function incrClicks($hash){
        $data = $this->findOneBy(
            array(
                'shortUrl'=>$hash
            )
        );
        if(is_null($data)){
            return null;
        }
        $clicks = $data->getClicks();
        $clicks++;
        $data->setClicks($clicks);
        $this->getEntityManager()->flush();
    }
}
